In [16]:
from dags.data_engineering_pipeline import extract_from_postgres, extract_from_csv, load_into_final_database, execute_query
import warnings
warnings.filterwarnings("ignore")

# Step 1
Write data to local disk

In [17]:

extract_from_postgres()
extract_from_csv()

Data extracted from table 'suppliers' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/suppliers/2023-08-22/suppliers.csv
Data extracted from table 'employees' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/employees/2023-08-22/employees.csv
Data extracted from table 'shippers' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/shippers/2023-08-22/shippers.csv
Data extracted from table 'categories' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/categories/2023-08-22/categories.csv
Data extracted from table 'employee_territories' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/employee_territories/2023-08-22/employee_territories.csv
Data extracted from table 'region' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/region/2023-08-22/region.csv
Data extracted from table 'customer_demographics' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/customer_demographics/2023-08-22/customer_demographics.csv
Data extracted from table 'us_states' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/us_states/2023-08-22/us_states.csv
Data extracted from table 'products' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/products/2023-08-22/products.csv
Data extracted from table 'territories' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/territories/2023-08-22/territories.csv
Data extracted from table 'customer_customer_demo' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/customer_customer_demo/2023-08-22/customer_customer_demo.csv
Data extracted from table 'customers' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/customers/2023-08-22/customers.csv
Data extracted from table 'orders' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/orders/2023-08-22/orders.csv
Data extracted from table 'order_details' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/postgres/order_details/2023-08-22/order_details.csv
Data extracted from CSV file '/home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/order_details.csv' and saved to /home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/csv/2023-08-22/order_details.csv

['/home/njoppi2/projetos/pessoal/data-pipeline/dags/../data/csv/2023-08-22/order_details.csv']

# Step 2
Load data to final database

In [18]:
load_into_final_database()

Didn't create database: CREATE DATABASE cannot run inside a transaction block

Data loaded into table 'suppliers' in the target database.
Data loaded into table 'employees' in the target database.
Data loaded into table 'shippers' in the target database.
Data loaded into table 'categories' in the target database.
Data loaded into table 'employee_territories' in the target database.
Data loaded into table 'region' in the target database.
Data loaded into table 'customer_demographics' in the target database.
Data loaded into table 'us_states' in the target database.
Data loaded into table 'products' in the target database.
Data loaded into table 'territories' in the target database.
Data loaded into table 'customer_customer_demo' in the target database.
Data loaded into table 'customers' in the target database.
Data loaded into table 'orders' in the target database.
Data loaded into table 'order_details' in the target database.

# Final query
Show the orders and its details

In [19]:
execute_query('''
    SELECT *
    FROM public.orders AS o
    LEFT JOIN public.order_details AS od ON o.order_id = od.order_id
    LIMIT 20
''')

,order_id,customer_id,employee_id,order_date,required_date,shipped_date,ship_via,freight,ship_name,ship_address,ship_city,ship_region,ship_postal_code,ship_country,order_id,product_id,unit_price,quantity,discount
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,None,51100,France,10248,11,14.0,12,0.00
1,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,None,51100,France,10248,42,9.8,10,0.00
2,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,None,51100,France,10248,72,34.8,5,0.00
3,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,None,44087,Germany,10249,14,18.6,9,0.00
4,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,None,44087,Germany,10249,51,42.4,40,0.00
5,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,10250,41,7.7,10,0.00
6,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,10250,51,42.4,35,0.15
7,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,10250,65,16.8,15,0.15
8,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,None,69004,France,10251,22,16.8,6,0.05
9,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,None,69004,France,10251,57,15.6,15,0.05
10,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,None,69004,France,10251,65,16.8,20,0.00
11,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,None,B-6000,Belgium,10252,20,64.8,40,0.05
12,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,None,B-6000,Belgium,10252,33,2.0,25,0.05
13,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,None,B-6000,Belgium,10252,60,27.2,40,0.00
14,10253,HANAR,3,1996-07-10,1996-07-24,1996-07-16,2,58.17,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,10253,31,10.0,20,0.00
15,10253,HANAR,3,1996-07-10,1996-07-24,1996-07-16,2,58.17,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,10253,39,14.4,42,0.00
16,10253,HANAR,3,1996-07-10,1996-07-24,1996-07-16,2,58.17,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil,10253,49,16.0,40,0.00
17,10254,CHOPS,5,1996-07-11,1996-08-08,1996-07-23,2,22.98,Chop-suey Chinese,Hauptstr. 31,Bern,None,3012,Switzerland,10254,24,3.6,15,0.15
18,10254,CHOPS,5,1996-07-11,1996-08-08,1996-07-23,2,22.98,Chop-suey Chinese,Hauptstr. 31,Bern,None,3012,Switzerland,10254,55,19.2,21,0.15
19,10254,CHOPS,5,1996-07-11,1996-08-08,1996-07-23,2,22.98,Chop-suey Chinese,Hauptstr. 31,Bern,None,3012,Switzerland,10254,74,8.0,21,0.00